# Generated by Django 2.2.16 on 2022-02-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220206_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы'
            },
        ),
    ]
